
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    env_file:
      - .env.example
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - DEBUG=1
      # - DOCKER_HOST=unix:///var/run/docker.sock
      # - SERVICES=s3,ec2,iam,cloudwatch
    # volumes:
    #   - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    #   - "./localstack:/var/lib/localstack"
    #   - "/var/run/docker.sock:/var/run/docker.sock"
     
