
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    env_file:
      - .env.example
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - DEBUG=1
      - SERVICES=s3,ec2,iam,cloudwatch
  
  terraform:
    image: hashicorp/terraform
    container_name: terraform
    env_file:
      - .env.example
    environment:
      - DEBUG=1
    volumes:
      - ./terraform:/terraform
    working_dir: /terraform
    entrypoint: sh
    command: ["-c", "terraform init -input=false && terraform apply -auto-approve -input=false -var-file=./environments/env.tfvars"]
    depends_on:
      - localstack

  app:
    build:
      context: ./application
      dockerfile: Dockerfile
    container_name: simple_app
    env_file:
      - .env.example
    ports:
      - "8000:8000"
    depends_on:
      - terraform
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - app
     
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./monitoring/grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./monitoring/grafana/dashboards/infrastructure.json:/etc/grafana/dashboards/infrastructure/infrastructure.json
      - ./monitoring/grafana/dashboards/business.json:/etc/grafana/dashboards/business/business.json
    depends_on:
      - prometheus