
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    env_file:
      - .env.example
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - DEBUG=1
      - SERVICES=s3,ec2,iam,cloudwatch
      # - DOCKER_HOST=unix:///var/run/docker.sock
    # volumes:
    #   - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    #   - "./localstack:/var/lib/localstack"
    #   - "/var/run/docker.sock:/var/run/docker.sock"
  
  terraform:
    image: hashicorp/terraform
    container_name: terraform
    platform: linux/arm64
    env_file:
      - .env.example
    environment:
      - DEBUG=1
    volumes:
      - ./terraform:/terraform
    working_dir: /terraform
    entrypoint: /bin/sh
    command: -c "terraform init -input=false && terraform apply -auto-approve -input=false"
    depends_on:
      - localstack

  app:
    build:
      context: ./application
      dockerfile: Dockerfile
    container_name: my_app
    env_file:
      - .env.example
    ports:
      - "8000:8000"
    depends_on:
      - terraform
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - app
     
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./monitoring/grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus


volumes:
  grafana-storage:
